In [71]:
# Always start at base directory for imports
%cd
%cd dev1/scaling-laws-ecnn/
import pandas as pd
pd.set_option('display.max_columns', None)
import torch
from typing import List


import sys
import os
# issue with https://github.com/pytorch/pytorch/issues/37377
os.environ["MKL_THREADING_LAYER"]="GNU"
sys.path.append(f"{os.getcwd()}")
#sys.path.append(f"..")
from experiments.b_NAS.common_best_architecture.util import *
from experiments.b_NAS.util import *
from experiments.run_command import run_command

%load_ext autoreload
%autoreload 2

/home/frischs
/home/frischs/dev1/scaling-laws-ecnn
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [5]:
choice_2_range_params = {
    "group": [1, 2, 4, 8, 16],
}
device = torch.device('cuda' if torch.cuda.is_available() else "cpu")
save_folder = "experiments/b_NAS/data/common_best_architecture/"

In [6]:
isic2019_client = get_ax_client_from_folder(folder = "isic2019_4")
galaxy10_client = get_ax_client_from_folder(folder = "galaxy10_weighted_folder_2")
cifar10_client = get_ax_client_from_folder(folder = "cifar10_2.2")
mnist_rot_client = get_ax_client_from_folder(folder = "mnist_rot_2.2")

Largest version:  0 ax_client_0.json

/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "-1_expand_ratio". Defaulting to `True` for parameters of `ParameterType` INT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "-1_dropout_rate". Defaulting to `True` for parameters of `ParameterType` FLOAT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "0_kernel_size". Defaulting to `True` for parameters of `ParameterType` INT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "1_conv_op". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "1_kernel_size". Defaulting to `True` for parameters of `ParameterType` INT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "1_se_ratio". Defaulting to `True` for parameters of `ParameterType` FLOAT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "1_skip_op". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "2_conv_op". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "2_kernel_size". Defaulting to `True` for parameters of `ParameterType` INT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "2_se_ratio". Defaulting to `True` for parameters of `ParameterType` FLOAT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "2_skip_op". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "3_conv_op". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "3_kernel_size". Defaulting to `True` for parameters of `ParameterType` INT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "3_se_ratio". Defaulting to `True` for parameters of `ParameterType` FLOAT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "3_skip_op". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "4_kernel_size". Defaulting to `True` for parameters of `ParameterType` INT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
[INFO 09-20 16:30:58] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "-1_expand_ratio". Defaulting to `True` for parameters of `ParameterType` INT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "-1_dropout_rate". Defaulting to `True` for parameters of `ParameterType` FLOAT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "0_kernel_size". Defaulting to `True` for parameters of `ParameterType` INT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "1_conv_op". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "1_kernel_size". Defaulting to `True` for parameters of `ParameterType` INT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "1_se_ratio". Defaulting to `True` for parameters of `ParameterType` FLOAT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "1_skip_op". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "2_conv_op". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "2_kernel_size". Defaulting to `True` for parameters of `ParameterType` INT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "2_se_ratio". Defaulting to `True` for parameters of `ParameterType` FLOAT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "2_skip_op". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "3_conv_op". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "3_kernel_size". Defaulting to `True` for parameters of `ParameterType` INT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "3_se_ratio". Defaulting to `True` for parameters of `ParameterType` FLOAT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "3_skip_op". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "4_kernel_size". Defaulting to `True` for parameters of `ParameterType` INT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(

Largest version:  5 ax_client_5.json

[INFO 09-20 16:30:58] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "-1_expand_ratio". Defaulting to `True` for parameters of `ParameterType` INT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "-1_dropout_rate". Defaulting to `True` for parameters of `ParameterType` FLOAT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "0_kernel_size". Defaulting to `True` for parameters of `ParameterType` INT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "1_conv_op". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "1_kernel_size". Defaulting to `True` for parameters of `ParameterType` INT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "1_se_ratio". Defaulting to `True` for parameters of `ParameterType` FLOAT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "1_skip_op". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "2_conv_op". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "2_kernel_size". Defaulting to `True` for parameters of `ParameterType` INT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "2_se_ratio". Defaulting to `True` for parameters of `ParameterType` FLOAT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "2_skip_op". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "3_conv_op". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "3_kernel_size". Defaulting to `True` for parameters of `ParameterType` INT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "3_se_ratio". Defaulting to `True` for parameters of `ParameterType` FLOAT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "3_skip_op". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "4_kernel_size". Defaulting to `True` for parameters of `ParameterType` INT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(

Largest version:  0 ax_client.json

[INFO 09-20 16:30:59] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "-1_expand_ratio". Defaulting to `True` for parameters of `ParameterType` INT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "-1_dropout_rate". Defaulting to `True` for parameters of `ParameterType` FLOAT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "0_kernel_size". Defaulting to `True` for parameters of `ParameterType` INT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "1_conv_op". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "1_kernel_size". Defaulting to `True` for parameters of `ParameterType` INT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "1_se_ratio". Defaulting to `True` for parameters of `ParameterType` FLOAT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "1_skip_op". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "2_conv_op". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "2_kernel_size". Defaulting to `True` for parameters of `ParameterType` INT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "2_se_ratio". Defaulting to `True` for parameters of `ParameterType` FLOAT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "2_skip_op". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "3_conv_op". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "3_kernel_size". Defaulting to `True` for parameters of `ParameterType` INT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "3_se_ratio". Defaulting to `True` for parameters of `ParameterType` FLOAT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "3_skip_op". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(
/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/core/parameter.py:511: UserWarning: `sort_values` is not specified for `ChoiceParameter` "4_kernel_size". Defaulting to `True` for parameters of `ParameterType` INT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  warn(

Largest version:  0 ax_client.json

[INFO 09-20 16:30:59] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.

In [10]:
show_experiment_ordered_frame(isic2019_client).head(5)

,trial_index,arm_name,trial_status,generation_method,gflops,model_building_time,valid_acc_weighted,is_feasible,-1_expand_ratio,-1_dropout_rate,0_reflection,0_group,0_out_channels,0_kernel_size,0_stride,1_reflection,1_group,1_num_layers,1_conv_op,1_kernel_size,1_se_ratio,1_out_channels,1_skip_op,1_stride,2_reflection,2_group,2_num_layers,2_conv_op,2_kernel_size,2_se_ratio,2_out_channels,2_skip_op,2_stride,3_reflection,3_group,3_num_layers,3_conv_op,3_kernel_size,3_se_ratio,3_out_channels,3_skip_op,3_stride,4_reflection,4_group,4_out_channels,4_kernel_size,4_stride
99,99,99_0,COMPLETED,FullyBayesianMOO,177.302962,42.532784,0.686486,True,6,0.5,0,2,1.000000,5,1,0,2,1,mbconv,5,0.0,3.954608,no,2,0,2,2,mbconv,5,0.0,2.710881,conv,2,-1,1,2,mbconv,5,0.75,1.0,conv,1,-1,0,1.191939,0,1
95,95,95_0,COMPLETED,FullyBayesianMOO,182.820076,42.969730,0.670074,True,6,0.5,0,2,1.000000,5,1,0,2,1,mbconv,5,0.0,3.989064,no,2,0,2,2,mbconv,5,0.0,2.697229,conv,2,-1,1,2,mbconv,5,0.75,1.0,conv,1,-1,0,1.000000,0,1
93,93,93_0,COMPLETED,FullyBayesianMOO,184.450179,42.912020,0.668099,True,6,0.5,0,2,1.000000,5,1,0,2,1,mbconv,5,0.0,3.898742,no,2,0,2,2,mbconv,5,0.0,2.799048,conv,2,-1,1,2,mbconv,5,0.75,1.0,conv,1,-1,0,1.139980,0,1
94,94,94_0,COMPLETED,FullyBayesianMOO,184.450179,43.790764,0.667049,True,6,0.5,0,2,1.000000,5,1,0,2,1,mbconv,5,0.0,3.895441,no,2,0,2,2,mbconv,5,0.0,2.800786,conv,2,-1,1,2,mbconv,5,0.75,1.0,conv,1,-1,0,1.156009,0,1
90,90,90_0,COMPLETED,FullyBayesianMOO,198.551230,44.450752,0.666404,True,6,0.5,0,2,1.019025,5,1,0,2,1,mbconv,5,0.0,3.739853,no,2,0,2,2,mbconv,5,0.0,3.013797,conv,2,-1,1,2,mbconv,5,0.75,1.0,conv,1,-1,0,1.000000,0,1

In [16]:
mnist_rot_final = optimal_experiment_trials(mnist_rot_client, 0.02, 10)
cifar10_final = optimal_experiment_trials(cifar10_client, 0.02, 10)
galaxy10_final = optimal_experiment_trials(galaxy10_client, 0.02, 10)
isic2019_final = optimal_experiment_trials(isic2019_client, 0.05, 10)
isic2019_final

[INFO 09-20 16:40:34] ax.modelbridge.base: Leaving out out-of-design observations for arms: 49_0, 73_0, 68_0

Optimizing for:  valid_acc

/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/modelbridge/modelbridge_utils.py:854: UserWarning: FYI: The default behavior of `get_pareto_frontier_and_configs` when `transform_outcomes_and_configs` is not specified has changed. Previously, the default was `transform_outcomes_and_configs=True`; now this argument is deprecated and behavior is as if `transform_outcomes_and_configs=False`. You did not specify `transform_outcomes_and_configs`, so this warning requires no action.
  warnings.warn(

Optimizing for:  valid_acc

/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/modelbridge/modelbridge_utils.py:854: UserWarning: FYI: The default behavior of `get_pareto_frontier_and_configs` when `transform_outcomes_and_configs` is not specified has changed. Previously, the default was `transform_outcomes_and_configs=True`; now this argument is deprecated and behavior is as if `transform_outcomes_and_configs=False`. You did not specify `transform_outcomes_and_configs`, so this warning requires no action.
  warnings.warn(
[WARNING 09-20 16:40:37] ax.modelbridge.modelbridge_utils: ObservationData(metric_names=['model_building_time'], means=[600.], covariance=[[nan]]) is missing the metrics {'gflops', 'valid_acc'}. Ignoring the data for the remaining metrics.
[INFO 09-20 16:40:37] ax.modelbridge.base: Leaving out out-of-design observations for arms: 97_0

Optimizing for:  valid_acc_weighted

/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/modelbridge/modelbridge_utils.py:854: UserWarning: FYI: The default behavior of `get_pareto_frontier_and_configs` when `transform_outcomes_and_configs` is not specified has changed. Previously, the default was `transform_outcomes_and_configs=True`; now this argument is deprecated and behavior is as if `transform_outcomes_and_configs=False`. You did not specify `transform_outcomes_and_configs`, so this warning requires no action.
  warnings.warn(
[INFO 09-20 16:40:41] ax.modelbridge.base: Leaving out out-of-design observations for arms: 91_0, 99_0, 90_0, 93_0

Optimizing for:  valid_acc_weighted

/home/frischs/anaconda3/envs/scaling-test/lib/python3.11/site-packages/ax/modelbridge/modelbridge_utils.py:854: UserWarning: FYI: The default behavior of `get_pareto_frontier_and_configs` when `transform_outcomes_and_configs` is not specified has changed. Previously, the default was `transform_outcomes_and_configs=True`; now this argument is deprecated and behavior is as if `transform_outcomes_and_configs=False`. You did not specify `transform_outcomes_and_configs`, so this warning requires no action.
  warnings.warn(

,trial_index,arm_name,trial_status,generation_method,gflops,model_building_time,valid_acc_weighted,is_feasible,-1_expand_ratio,-1_dropout_rate,0_reflection,0_group,0_out_channels,0_kernel_size,0_stride,1_reflection,1_group,1_num_layers,1_conv_op,1_kernel_size,1_se_ratio,1_out_channels,1_skip_op,1_stride,2_reflection,2_group,2_num_layers,2_conv_op,2_kernel_size,2_se_ratio,2_out_channels,2_skip_op,2_stride,3_reflection,3_group,3_num_layers,3_conv_op,3_kernel_size,3_se_ratio,3_out_channels,3_skip_op,3_stride,4_reflection,4_group,4_out_channels,4_kernel_size,4_stride
99,99,99_0,COMPLETED,FullyBayesianMOO,177.302962,42.532784,0.686486,True,6,0.5,0,2,1.000000,5,1,0,2,1,mbconv,5,0.0,3.954608,no,2,0,2,2,mbconv,5,0.0,2.710881,conv,2,-1,1,2,mbconv,5,0.75,1.0,conv,1,-1,0,1.191939,0,1
95,95,95_0,COMPLETED,FullyBayesianMOO,182.820076,42.969730,0.670074,True,6,0.5,0,2,1.000000,5,1,0,2,1,mbconv,5,0.0,3.989064,no,2,0,2,2,mbconv,5,0.0,2.697229,conv,2,-1,1,2,mbconv,5,0.75,1.0,conv,1,-1,0,1.000000,0,1
93,93,93_0,COMPLETED,FullyBayesianMOO,184.450179,42.912020,0.668099,True,6,0.5,0,2,1.000000,5,1,0,2,1,mbconv,5,0.0,3.898742,no,2,0,2,2,mbconv,5,0.0,2.799048,conv,2,-1,1,2,mbconv,5,0.75,1.0,conv,1,-1,0,1.139980,0,1
94,94,94_0,COMPLETED,FullyBayesianMOO,184.450179,43.790764,0.667049,True,6,0.5,0,2,1.000000,5,1,0,2,1,mbconv,5,0.0,3.895441,no,2,0,2,2,mbconv,5,0.0,2.800786,conv,2,-1,1,2,mbconv,5,0.75,1.0,conv,1,-1,0,1.156009,0,1
90,90,90_0,COMPLETED,FullyBayesianMOO,198.551230,44.450752,0.666404,True,6,0.5,0,2,1.019025,5,1,0,2,1,mbconv,5,0.0,3.739853,no,2,0,2,2,mbconv,5,0.0,3.013797,conv,2,-1,1,2,mbconv,5,0.75,1.0,conv,1,-1,0,1.000000,0,1
87,87,87_0,COMPLETED,FullyBayesianMOO,174.111371,41.816144,0.664944,True,6,0.5,0,2,1.000000,5,1,0,2,1,mbconv,5,0.0,4.000000,no,2,0,2,2,mbconv,5,0.0,2.613370,conv,2,-1,1,2,mbconv,5,0.75,1.0,conv,1,-1,0,1.376464,0,2
92,92,92_0,COMPLETED,FullyBayesianMOO,189.424284,43.786145,0.658241,True,6,0.5,0,2,1.000000,5,1,0,2,1,mbconv,5,0.0,3.811296,no,2,0,2,2,mbconv,5,0.0,2.947719,conv,2,-1,1,2,mbconv,5,0.75,1.0,conv,1,-1,0,1.000000,0,1
97,97,97_0,COMPLETED,FullyBayesianMOO,186.092290,42.916104,0.654906,True,6,0.5,0,2,1.000000,5,1,0,2,1,mbconv,5,0.0,3.902219,no,2,0,2,2,mbconv,5,0.0,2.819601,conv,2,-1,1,2,mbconv,5,0.75,1.0,conv,1,-1,0,1.000000,0,1
96,96,96_0,COMPLETED,FullyBayesianMOO,186.092290,42.403900,0.652675,True,6,0.5,0,2,1.000000,5,1,0,2,1,mbconv,5,0.0,3.883796,no,2,0,2,2,mbconv,5,0.0,2.845560,conv,2,-1,1,2,mbconv,5,0.75,1.0,conv,1,-1,0,1.000000,0,1

In [28]:
isic2019_final

Empty DataFrame
Columns: [trial_index, arm_name, trial_status, generation_method, gflops, model_building_time, valid_acc_weighted, is_feasible, -1_expand_ratio, -1_dropout_rate, 0_reflection, 0_group, 0_out_channels, 0_kernel_size, 0_stride, 1_reflection, 1_group, 1_num_layers, 1_conv_op, 1_kernel_size, 1_se_ratio, 1_out_channels, 1_skip_op, 1_stride, 2_reflection, 2_group, 2_num_layers, 2_conv_op, 2_kernel_size, 2_se_ratio, 2_out_channels, 2_skip_op, 2_stride, 3_reflection, 3_group, 3_num_layers, 3_conv_op, 3_kernel_size, 3_se_ratio, 3_out_channels, 3_skip_op, 3_stride, 4_reflection, 4_group, 4_out_channels, 4_kernel_size, 4_stride]
Index: []

In [49]:
mnist_rot_final.to_csv(save_folder + 'mnist_rot_selected_best.csv', index=True, header=True)
cifar10_final.to_csv(save_folder + 'cifar10_selected_best.csv', index=True, header=True)
galaxy10_final.to_csv(save_folder + 'galaxy10_selected_best.csv', index=True, header=True)
isic2019_final.to_csv(save_folder + 'isic2019_selected_best.csv', index=True, header=True)

In [22]:
summary_df = summarize_optimal_architectures(isic2019_final, valid_acc_weight=0.8)  # 0.8 is the weight for valid_acc in the averaging
summary_df

,gflops,valid_acc_weighted,-1_expand_ratio,-1_dropout_rate,0_reflection,0_group,0_out_channels,0_kernel_size,0_stride,1_reflection,1_group,1_num_layers,1_conv_op,1_kernel_size,1_se_ratio,1_out_channels,1_skip_op,1_stride,2_reflection,2_group,2_num_layers,2_conv_op,2_kernel_size,2_se_ratio,2_out_channels,2_skip_op,2_stride,3_reflection,3_group,3_num_layers,3_conv_op,3_kernel_size,3_se_ratio,3_out_channels,3_skip_op,3_stride,4_reflection,4_group,4_out_channels,4_kernel_size,4_stride
weighted_average,184.290921,0.670217,6.0,0.5,0.0,2.0,1.002831,5.0,1.0,0.0,2.0,1.0,mbconv=100%;,5.0,0.0,3.901752,no=100%;,2.0,0.0,2.0,2.0,mbconv=100%;,5.0,0.0,2.794591,conv=100%;,2.0,-1.0,1.0,2.0,mbconv=100%;,5.0,0.75,1.0,conv=100%;,1.0,-1.0,0.0,1.112862,0.0,1.083552

In [36]:
isic2019_final[isic2019_final['trial_index'] == 99]

,trial_index,arm_name,trial_status,generation_method,gflops,model_building_time,valid_acc_weighted,is_feasible,-1_expand_ratio,-1_dropout_rate,0_reflection,0_group,0_out_channels,0_kernel_size,0_stride,1_reflection,1_group,1_num_layers,1_conv_op,1_kernel_size,1_se_ratio,1_out_channels,1_skip_op,1_stride,2_reflection,2_group,2_num_layers,2_conv_op,2_kernel_size,2_se_ratio,2_out_channels,2_skip_op,2_stride,3_reflection,3_group,3_num_layers,3_conv_op,3_kernel_size,3_se_ratio,3_out_channels,3_skip_op,3_stride,4_reflection,4_group,4_out_channels,4_kernel_size,4_stride
99,99,99_0,COMPLETED,FullyBayesianMOO,177.302962,42.532784,0.686486,True,6,0.5,0,2,1.0,5,1,0,2,1,mbconv,5,0.0,3.954608,no,2,0,2,2,mbconv,5,0.0,2.710881,conv,2,-1,1,2,mbconv,5,0.75,1.0,conv,1,-1,0,1.191939,0,1

In [37]:
pd.concat([isic2019_final[isic2019_final['trial_index'] == 99], summary_df], axis=0)

,trial_index,arm_name,trial_status,generation_method,gflops,model_building_time,valid_acc_weighted,is_feasible,-1_expand_ratio,-1_dropout_rate,0_reflection,0_group,0_out_channels,0_kernel_size,0_stride,1_reflection,1_group,1_num_layers,1_conv_op,1_kernel_size,1_se_ratio,1_out_channels,1_skip_op,1_stride,2_reflection,2_group,2_num_layers,2_conv_op,2_kernel_size,2_se_ratio,2_out_channels,2_skip_op,2_stride,3_reflection,3_group,3_num_layers,3_conv_op,3_kernel_size,3_se_ratio,3_out_channels,3_skip_op,3_stride,4_reflection,4_group,4_out_channels,4_kernel_size,4_stride
99,99.0,99_0,COMPLETED,FullyBayesianMOO,177.302962,42.532784,0.686486,True,6.0,0.5,0.0,2.0,1.000000,5.0,1.0,0.0,2.0,1.0,mbconv,5.0,0.0,3.954608,no,2.0,0.0,2.0,2.0,mbconv,5.0,0.0,2.710881,conv,2.0,-1.0,1.0,2.0,mbconv,5.0,0.75,1.0,conv,1.0,-1.0,0.0,1.191939,0.0,1.000000
isic2019,NaN,NaN,NaN,NaN,184.290921,NaN,0.670217,NaN,6.0,0.5,0.0,2.0,1.002831,5.0,1.0,0.0,2.0,1.0,mbconv=100%;,5.0,0.0,3.901752,no=100%;,2.0,0.0,2.0,2.0,mbconv=100%;,5.0,0.0,2.794591,conv=100%;,2.0,-1.0,1.0,2.0,mbconv=100%;,5.0,0.75,1.0,conv=100%;,1.0,-1.0,0.0,1.112862,0.0,1.083552

In [72]:
best_not_adjusted_isic_2019 = isic2019_final[isic2019_final['trial_index'] == 99].iloc[:,8:]
best_not_adjusted_isic_2019.index = ["pure_isic2019_99_not_adjusted"]
best_not_adjusted_isic_2019
add_to_csv(best_not_adjusted_isic_2019, save_folder, 'strategies')

,-1_expand_ratio,-1_dropout_rate,0_reflection,0_group,0_out_channels,0_kernel_size,0_stride,1_reflection,1_group,1_num_layers,1_conv_op,1_kernel_size,1_se_ratio,1_out_channels,1_skip_op,1_stride,2_reflection,2_group,2_num_layers,2_conv_op,2_kernel_size,2_se_ratio,2_out_channels,2_skip_op,2_stride,3_reflection,3_group,3_num_layers,3_conv_op,3_kernel_size,3_se_ratio,3_out_channels,3_skip_op,3_stride,4_reflection,4_group,4_out_channels,4_kernel_size,4_stride
pure_isic2019_99_not_adjusted,6,0.5,0,2,1.0,5,1,0,2,1,mbconv,5,0.0,3.954608,no,2,0,2,2,mbconv,5,0.0,2.710881,conv,2,-1,1,2,mbconv,5,0.75,1.0,conv,1,-1,0,1.191939,0,1
pure_isic2019_99,6,0.5,0,2,1.0,5,1,0,2,1,mbconv,5,0.0,4.000000,no,2,0,2,2,mbconv,5,0.0,2.700000,conv,2,-1,1,2,mbconv,5,0.75,1.0,conv,1,-1,0,1.200000,0,1

In [ ]:
tmp = pd.read_csv(save_folder + 'strategies.csv', index_col=0)
tmp

In [61]:
best_strategy_isic2019 = apply_transformations(isic2019_final[isic2019_final['trial_index'] == 99].iloc[:,8:].copy(), round_to_float_01_mask=["dropout_rate", "out_channels"])
best_strategy_isic2019.index = ["pure_isic2019_99"]
best_strategy_isic2019.to_csv(save_folder + 'strategies.csv', index=True, header=True)

params {'no_round': ['gflops', 'valid_acc(_weighted)'], 'round_to_int': ['-1_expand_ratio', '0_reflection', '0_group', '0_kernel_size', '0_stride', '1_reflection', '1_group', '1_num_layers', '1_kernel_size', '1_stride', '2_reflection', '2_group', '2_num_layers', '2_kernel_size', '2_stride', '3_reflection', '3_group', '3_num_layers', '3_kernel_size', '3_stride', '4_reflection', '4_group', '4_kernel_size', '4_stride'], 'round_to_float_025': ['1_se_ratio', '2_se_ratio', '3_se_ratio'], 'categorical': ['1_conv_op', '1_skip_op', '2_conv_op', '2_skip_op', '3_conv_op', '3_skip_op'], 'round_to_float_01': ['-1_dropout_rate', '0_out_channels', '1_out_channels', '2_out_channels', '3_out_channels', '4_out_channels']}

In [24]:
# List of DataFrames
dataframes = [mnist_rot_final, cifar10_final, galaxy10_final, isic2019_final]  # Replace these with your actual DataFrames
dataset_names = ['mnist_rot', 'cifar10', 'galaxy10', 'isic2019']
valid_acc_weight = 0.8

# Create a list of summary DataFrames
summary_dfs = []
for name, to_add_df in zip(dataset_names, dataframes):
    summary_dfs.append(summarize_optimal_architectures(to_add_df, valid_acc_weight=valid_acc_weight))

#summary_dfs = [summarize_optimal_architectures(df, valid_acc_weight=valid_acc_weight) for name, df in zip(dataset_names, dataframes) if name]

# Set the dataset name as the index for each summary DataFrame
for name, summary_df in zip(dataset_names, summary_dfs):
    summary_df.index = [name]

# Concatenate the summary DataFrames into one
final_summary_df = pd.concat(summary_dfs)

# Now you can print or use final_summary_df
final_summary_df

final_summary_df["valid_acc(_weighted)"] = final_summary_df["valid_acc"].combine_first(final_summary_df["valid_acc_weighted"])
final_summary_df = final_summary_df.drop(columns=["valid_acc", "valid_acc_weighted"])
# Get the last column name
last_column_name = final_summary_df.columns[-1]
# Create a list of column names with the last column in the second position
new_column_order = [final_summary_df.columns[0], last_column_name] + list(final_summary_df.columns[1:-1])
# Reorder the columns based on the new order
final_summary_df = final_summary_df[new_column_order]
final_summary_df


#final_summary_df

,gflops,valid_acc(_weighted),-1_expand_ratio,-1_dropout_rate,0_reflection,0_group,0_out_channels,0_kernel_size,0_stride,1_reflection,1_group,1_num_layers,1_conv_op,1_kernel_size,1_se_ratio,1_out_channels,1_skip_op,1_stride,2_reflection,2_group,2_num_layers,2_conv_op,2_kernel_size,2_se_ratio,2_out_channels,2_skip_op,2_stride,3_reflection,3_group,3_num_layers,3_conv_op,3_kernel_size,3_se_ratio,3_out_channels,3_skip_op,3_stride,4_reflection,4_group,4_out_channels,4_kernel_size,4_stride
mnist_rot,9.407440,0.997071,5.846607,0.000000,-0.871267,3.935387,2.418844,5.0,2.0,-0.871267,3.935387,1.752187,dconv=17%; mbconv=82%;,3.062208,0.02423,3.258303,conv=83%; identity=9%; no=7%;,1.579063,-1.000000,3.807597,1.837566,dconv=33%; mbconv=66%;,4.897813,0.678673,1.016860,conv=26%; identity=63%; no=9%;,1.001202,-1.000000,3.807597,1.254485,conv=64%; dconv=3%; mbconv=32%;,5.0,0.039504,1.168088,conv=27%; identity=51%; no=21%;,2.0,-1.000000,3.742985,1.170697,4.838469,1.750886
cifar10,35.972969,0.910561,6.000000,0.000000,0.000000,4.000000,1.494722,5.0,2.0,0.000000,4.000000,1.464759,mbconv=100%;,3.000000,0.75000,2.502670,conv=100%;,1.000000,-0.266253,2.510712,1.000000,conv=91%; dconv=8%;,3.000000,0.549517,3.831393,no=100%;,1.000000,-0.432444,1.219449,2.000000,mbconv=100%;,5.0,0.593377,1.098077,conv=25%; identity=47%; no=26%;,2.0,-0.830394,0.977533,1.015675,4.310530,1.602050
galaxy10,1325.831644,0.818408,4.004156,0.299792,0.000000,0.004156,1.000000,5.0,1.0,0.000000,0.000000,1.882295,dconv=24%; mbconv=75%;,3.000000,0.00000,3.534274,conv=99%; identity=0%;,2.000000,0.000000,0.000000,2.000000,conv=100%;,5.000000,0.000000,2.544688,no=100%;,1.000000,0.000000,0.000000,2.000000,conv=100%;,5.0,0.750000,2.317146,identity=100%;,2.0,0.000000,0.000000,1.000000,3.000000,1.000000
isic2019,184.290921,0.670217,6.000000,0.500000,0.000000,2.000000,1.002831,5.0,1.0,0.000000,2.000000,1.000000,mbconv=100%;,5.000000,0.00000,3.901752,no=100%;,2.000000,0.000000,2.000000,2.000000,mbconv=100%;,5.000000,0.000000,2.794591,conv=100%;,2.000000,-1.000000,1.000000,2.000000,mbconv=100%;,5.0,0.750000,1.000000,conv=100%;,1.0,-1.000000,0.000000,1.112862,0.000000,1.083552

In [55]:
# save result_df to csv
final_summary_df.to_csv(save_folder + 'weighted_average_summaries.csv', index=True, header=True)

In [56]:
final_summary_df

,gflops,valid_acc(_weighted),-1_expand_ratio,-1_dropout_rate,0_reflection,0_group,0_out_channels,0_kernel_size,0_stride,1_reflection,1_group,1_num_layers,1_conv_op,1_kernel_size,1_se_ratio,1_out_channels,1_skip_op,1_stride,2_reflection,2_group,2_num_layers,2_conv_op,2_kernel_size,2_se_ratio,2_out_channels,2_skip_op,2_stride,3_reflection,3_group,3_num_layers,3_conv_op,3_kernel_size,3_se_ratio,3_out_channels,3_skip_op,3_stride,4_reflection,4_group,4_out_channels,4_kernel_size,4_stride
mnist_rot,9.407440,0.997071,5.846607,0.000000,-0.871267,3.935387,2.418844,5.0,2.0,-0.871267,3.935387,1.752187,dconv=17%; mbconv=82%;,3.062208,0.02423,3.258303,conv=83%; identity=9%; no=7%;,1.579063,-1.000000,3.807597,1.837566,dconv=33%; mbconv=66%;,4.897813,0.678673,1.016860,conv=26%; identity=63%; no=9%;,1.001202,-1.000000,3.807597,1.254485,conv=64%; dconv=3%; mbconv=32%;,5.0,0.039504,1.168088,conv=27%; identity=51%; no=21%;,2.0,-1.000000,3.742985,1.170697,4.838469,1.750886
cifar10,35.972969,0.910561,6.000000,0.000000,0.000000,4.000000,1.494722,5.0,2.0,0.000000,4.000000,1.464759,mbconv=100%;,3.000000,0.75000,2.502670,conv=100%;,1.000000,-0.266253,2.510712,1.000000,conv=91%; dconv=8%;,3.000000,0.549517,3.831393,no=100%;,1.000000,-0.432444,1.219449,2.000000,mbconv=100%;,5.0,0.593377,1.098077,conv=25%; identity=47%; no=26%;,2.0,-0.830394,0.977533,1.015675,4.310530,1.602050
galaxy10,1325.831644,0.818408,4.004156,0.299792,0.000000,0.004156,1.000000,5.0,1.0,0.000000,0.000000,1.882295,dconv=24%; mbconv=75%;,3.000000,0.00000,3.534274,conv=99%; identity=0%;,2.000000,0.000000,0.000000,2.000000,conv=100%;,5.000000,0.000000,2.544688,no=100%;,1.000000,0.000000,0.000000,2.000000,conv=100%;,5.0,0.750000,2.317146,identity=100%;,2.0,0.000000,0.000000,1.000000,3.000000,1.000000
isic2019,184.290921,0.670217,6.000000,0.500000,0.000000,2.000000,1.002831,5.0,1.0,0.000000,2.000000,1.000000,mbconv=100%;,5.000000,0.00000,3.901752,no=100%;,2.000000,0.000000,2.000000,2.000000,mbconv=100%;,5.000000,0.000000,2.794591,conv=100%;,2.000000,-1.000000,1.000000,2.000000,mbconv=100%;,5.0,0.750000,1.000000,conv=100%;,1.0,-1.000000,0.000000,1.112862,0.000000,1.083552

In [42]:
# Apply transformations
result_df = apply_transformations(final_summary_df.copy())
result_df

Skipping gflops because it is already assigned
Skipping valid_acc(_weighted) because it is already assigned
Skipping -1_dropout_rate because it is already assigned

,gflops,valid_acc(_weighted),-1_expand_ratio,-1_dropout_rate,0_reflection,0_group,0_out_channels,0_kernel_size,0_stride,1_reflection,1_group,1_num_layers,1_conv_op,1_kernel_size,1_se_ratio,1_out_channels,1_skip_op,1_stride,2_reflection,2_group,2_num_layers,2_conv_op,2_kernel_size,2_se_ratio,2_out_channels,2_skip_op,2_stride,3_reflection,3_group,3_num_layers,3_conv_op,3_kernel_size,3_se_ratio,3_out_channels,3_skip_op,3_stride,4_reflection,4_group,4_out_channels,4_kernel_size,4_stride
pure_mnist_rot,9.407440,0.997071,6,0.0,-1,4,2.5,5,2,-1,4,2,mbconv,3,0.00,3.25,conv,2,-1,4,2,mbconv,5,0.75,1.00,identity,1,-1,4,1,conv,5,0.00,1.25,identity,2,-1,4,1.25,5,2
pure_cifar10,35.972969,0.910561,6,0.0,0,4,1.5,5,2,0,4,1,mbconv,3,0.75,2.50,conv,1,0,3,1,conv,3,0.50,3.75,no,1,0,1,2,mbconv,5,0.50,1.00,identity,2,-1,1,1.00,4,2
pure_galaxy10,1325.831644,0.818408,4,0.3,0,0,1.0,5,1,0,0,2,mbconv,3,0.00,3.50,conv,2,0,0,2,conv,5,0.00,2.50,no,1,0,0,2,conv,5,0.75,2.25,identity,2,0,0,1.00,3,1
pure_isic2019,184.290921,0.670217,6,0.5,0,2,1.0,5,1,0,2,1,mbconv,5,0.00,4.00,no,2,0,2,2,mbconv,5,0.00,2.75,conv,2,-1,1,2,mbconv,5,0.75,1.00,conv,1,-1,0,1.00,0,1

In [58]:
# save result_df to csv
result_df = result_df.drop(columns=["gflops", "valid_acc(_weighted)"])
result_df.to_csv(save_folder + 'pure_strategies.csv', index=True, header=True)

# load result_df from csv
tmp = pd.read_csv(save_folder + 'pure_strategies.csv', index_col=0)
tmp

,-1_expand_ratio,-1_dropout_rate,0_reflection,0_group,0_out_channels,0_kernel_size,0_stride,1_reflection,1_group,1_num_layers,1_conv_op,1_kernel_size,1_se_ratio,1_out_channels,1_skip_op,1_stride,2_reflection,2_group,2_num_layers,2_conv_op,2_kernel_size,2_se_ratio,2_out_channels,2_skip_op,2_stride,3_reflection,3_group,3_num_layers,3_conv_op,3_kernel_size,3_se_ratio,3_out_channels,3_skip_op,3_stride,4_reflection,4_group,4_out_channels,4_kernel_size,4_stride
pure_mnist_rot,6,0.0,-1,4,2.5,5,2,-1,4,2,mbconv,3,0.00,3.25,conv,2,-1,4,2,mbconv,5,0.75,1.00,identity,1,-1,4,1,conv,5,0.00,1.25,identity,2,-1,4,1.25,5,2
pure_cifar10,6,0.0,0,4,1.5,5,2,0,4,1,mbconv,3,0.75,2.50,conv,1,0,3,1,conv,3,0.50,3.75,no,1,0,1,2,mbconv,5,0.50,1.00,identity,2,-1,1,1.00,4,2
pure_galaxy10,4,0.3,0,0,1.0,5,1,0,0,2,mbconv,3,0.00,3.50,conv,2,0,0,2,conv,5,0.00,2.50,no,1,0,0,2,conv,5,0.75,2.25,identity,2,0,0,1.00,3,1
pure_isic2019,6,0.5,0,2,1.0,5,1,0,2,1,mbconv,5,0.00,4.00,no,2,0,2,2,mbconv,5,0.00,2.75,conv,2,-1,1,2,mbconv,5,0.75,1.00,conv,1,-1,0,1.00,0,1